---
name: minimaxis_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.3
  flutter_bloc: ^8.1.2
  flutter_modular: ^5.0.3
  provider: ^6.0.3
  flutter_webln: ^0.0.1
  qr_flutter: ^4.0.0
  fluttertoast: ^8.0.9
  confetti: ^0.7.0
  just_audio: ^0.9.29
  logger: ^2.0.2+1
  mermaid: ^0.9.35
  webview_flutter: ^2.0.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/