---
name: minimaxis_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  build_runner: ^2.3.3
  flutter_webln: ^0.0.1
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.1.0
  flutter_modular: ^5.0.3
  provider: ^6.0.3
  qr_flutter: ^4.0.0
  logger: ^2.0.2+1
  mermaid: ^0.9.35
  url_launcher: ^6.2.2
  http: ^1.1.0
  animated_text_kit: ^4.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env